name: Simple test

on:
  workflow_dispatch:

jobs:
  job-void-linux_void-musl:
  container: ghcr.io/void-linux/void-musl
  runs-on: ubuntu-latest
  steps:
    - name: Make artifact
      run: echo TEST > test.txt
    - name: Upload artifact job-void-linux_void-musl
      uses: actions/upload-artifact@v4
      with:
        name: job-void-linux_void-musl
        path: test.txt
